### ISSUE TITLE
Basic Dev Environment

### ISSUE THREAD

**Issue by carolclark** [cebcar/Tuxedo-ij#102]
#### > Basic DevOps Environment <
- workflows
- shell support
- developer access
  - cebcar terminology
    - accessibility: software supports adaptations as indicated for those with a variety of issues
      - the standard technical interpretation
    - devaccess: appropriate access for our developer, who has some manual limitations
- policies<br><br>

- [ ] document at environment/DevOps.md

#### >> toolset
- [ ] add toolset overview document tools/Toolset.md; categorize and link tools already documented

#### iTerm2 and oh-my-zsh
  *macOS terminal replacement with package manager for zsh*
  - [ ] add iTerm2_oh-my-zsh.md
    - iTerm2 and oh-my-zsh are frequently documented together because oh-my-zsh adds commands to iTerm2
