### ISSUE TITLE
Clean up Old Repos

### ISSUE THREAD

**Issue by carolclark** [cebcar/Tuxedo-ij#113]
##### cebcar
- [ ] close forks
  - [ ] cebcar.github.io <br><br>

- [ ] delete soon
  - [ ] DS1
  - [ ] DevOps-tryAgain
  - [ ] TuxedoX

##### carolclark
- [ ] discard tutorial projects
  - [ ] github-pages-with-jekyll
  - [ ] github-slideshow
  - [ ] desktop-tutorial
  - [ ] swift <br><br>

- [ ] close forks
  - [ ] gitignore.io
  - [ ] bats
  - [ ] testRel <br><br>

- [ ] delete soon
  - [ ] Toy Site
  - [ ] DevSupportX
  - [ ] DevOpsX
