### ISSUE TITLE
Recover from Branching Problem

### ISSUE THREAD

**Issue by carolclark** [cebcar/Tuxedo-ij#24]
### > Background <
The problem addressed here was that we had an existing bad branch in an IntelliJ repo.
We now believe that the problem was caused by inadequate branch maintenance.
Since then, we started using iTerm2 for branch maintenance, which made it easier to provide tighter branch control than our WebStorm workflow did.
- *WebStorm does have an available terminal window, but it lacked many features, including configuration support, that are available in the Terminal application. We were pasting in CLI aliases as a normal part of our workflow, and we learned that the 'current branch' button was not always up-to-date. WebStorm's snippet support is also widely recognized as inadequate, ... .*
- *The perceived git repo problem noted below was that we should have been fixing the git repo directly via CLI, instead of trying through either GitHub or WebStorm.*
<br><br>
### > Implementation <
complete
## >> Analysis : Original <<

Due to a bug in our workflow's use of IntelliJ Fetch in a new project, we had an existing bad branch in an IntelliJ repo.
We edited the repository in GitHub to remove the bad branch; only main and a single good branch remained.
But when we cloned the repository into IntelliJ,
some commits from the old bad branch reappeared in the IntelliJ Git tool, even after a Fetch.
These were active commits;
we hoped we could ignore them, but then a new commit accidentally appeared on the old bad branch.
In online searches, results included the commits below, but none addressed the issue that when we created a new Intellij repo based on the corrected GitHub repo, the bad commits still appeared in the new IntelliJ project.

We do not know where IntelliJ got the bad branch info, but maybe:
- it came from IntelliJ information about a previous project with the same name
- the GitHub project did not really delete the bad commits when we removed the extra branch

see:
- [Renaming a project in IntelliJ IDEA](https://stackoverflow.com/questions/21177495/renaming-a-project-in-intellij-idea), answer approx. cebcar/Tuxedo#3 headed "Following are the steps to be followed in IntelliJ Idea Community Edition:"
- [How to rename / move a project in Intellij Idea 12?](https://stackoverflow.com/questions/18493379/how-to-rename-move-a-project-in-intellij-idea-12) answer approx cebcar/Tuxedo#2 starting "Right click on project, then"
- [Set up a Git Repository: Put an existing project under Git version control﻿](https://www.jetbrains.com/help/idea/set-up-a-git-repository.html#clone-repo)

### > Submit Bug Report <
- submitted 23 Jun 2021; #272304 assigned to Ivan Semerov; [Bug Report Page](https://youtrack.jetbrains.com/issue/IDEA-272304)

### >> Recover GitHub Issues <<
- [x] print screenshot of current Board
- [x] rename existing repo project to Tuxedo-w-bad-branch
  - [x] in Project (c1) view, rename project from Tuxedo to Tuxedo-w-bad-branch
  - [x] quit IntelliJ
  - [-] rename the project folder in ~/Dev to match
    - skipped to avoid reopening the bad Tuxedo project
- [x] create new project Tuxedo

### >> When we have a good repository <<
- [x] new ZenHub Workspace Tuxedo
  - [x] create Workspace
  - [x] update column names and descriptions
  - [x] add GitHub labels
  - [x] GitHub: transfer each issue from Tuxedo-w-bad-branch to Tuxedo
  - [x] update Workspace from image of Tuxedo-w-bad-branch
    - [x] for each Epic
      - set pipeline Epic
      - add Epic labels
      - convert to Epic
    - [x] sort Epics
    - [x] add dependencies: cebcar/Tuxedo-w-bad-branch#38 requires cebcar/Tuxedo#23; cebcar/Tuxedo#2 requires cebcar/Tuxedo#15
    - [x] for each non-Epic pipeline; for each issue from bottom
      - set pipeline, labels, estimate, enclosing Epic

#### Recover Tuxedo Issues
- [x] Recover Tuxedo Issues #22 <br/><br/>

#### recreate project Tuxedo
- [x] recreate project Tuxedo #58 <br/>
*contains notes on changes needed to documentation*

#### documentation recovery and related changes
- [x] recover current Tuxedo docs #42 <br/><br/>

#### update docs with what we learned from and during Fetch problem
- docs since Fetch problem #34 was incorporated into #42<br/><br/>

#### Feature Branch WF to single branch #57
- [x] simplify Feature Branch WF to support only one branch at a time for now<br/><br/>
