### ISSUE TITLE
github issue labels

### ISSUE THREAD

**Issue by carolclark** [cebcar/Tuxedo-ij#3]
### github issue labels #3

establish standard default label set for cebcar GitHub/ZenHub projects

#### > Motivation
The label set we were using in DevOps was working very well. Adopt and continue.

#### > Implementation (Issues)

- [x] establish Tuxedo default issue labels
  - include: name; optional description; color
  - [x] color blocks
      - IntelliJ Live Template
        - see [How to Create a Colored Box in HTML/CSS](https://www.thesitewizard.com/css/create-coloured-box.shtml)
           - `<div style="background-color: #cfc ; padding: 10px; border: 1px solid green;">"Hello, World!"</div>` 
           displays as expected under Markdown Navigator Enhanced
  - [x] entities/RepoProject: start with existing labels from project recent_devops
  - [x] review; edit if indicated
  - [x] implement resulting labels in Tuxedo

#### >> Update Labels
- [ ] adjust labels #32

#### >> After using those labels for awhile:
- [ ] establish cebcar default issue labels
  - establish default label set for cebcar ZenHub/GitHub projects
    - see [GitHub: Managing default labels for repositories in your organization](https://docs.github.com/en/organizations/managing-organization-settings/managing-default-labels-for-repositories-in-your-organization)
