### ISSUE TITLE
Planning Support

### ISSUE THREAD

**Issue by carolclark** [cebcar/Tuxedo-ij#31]
#### Board Tuxedo plan
possible pipelines:
- Thoughts: pain points; possible new development; ... (Initiative Epic)
- Ideas: possible approaches (may add Initiative Epics)
- Solutions: proposed solutions (may add Initiative Epics)
- Decision: Initiatives to be pursued (Initiative Epics)
- Initiatives: initiative planning; Roadmap Epic generation)
- Roadmap Initiatives: 
- to Roadmap: Roadmap Initiatives (Roadmap projects) to be moved to Roadmap for further planning and development

#### Roadmap (Roadmap Epics in; Standard Epics generated)
flesh out Roadmap Epics for implementation; generates standard Epics

#### Board Tuxedo dev
includes active Roadmap Epics in column Roadmap for reference
development proceeds with standard Epics

### > Implementation <
- [ ] review (add date)
- [ ] review (add date)
- [ ] new Board Tuxedo plan
- [ ] add column Roadmap to Board Tuxedo dev

**Comment by carolclark** [comment]
We are no longer supporting a planning level above Roadmap. We do have a PlantUML diagram that can include additional planned items.

Closing
