### ISSUE TITLE
Inspect Markdown

### ISSUE THREAD

**Issue by carolclark** [cebcar/Tuxedo-ij#36]
### Inspect Markdown #36

Files are now being committed when they pass **commit** inspection.
Require complete Inspections to pass.

### > Background <
- git commit check does some, but not complete, inspections
- full Inspections will check all files, not just changed files <br/><br/>

- we previously made changes to IntelliJ Inspections to get inspections to pass
- however, we tried to fix inspections all at once, before continuing with other work
  - we did not really understand the choices
    - especially: ctrl-click on inspection in Annotator list to exclude that specific item only
  - changes made were not documented <br><br>

- clear existing Proofreading settings and start from scratch to correct <br/><br/>

- we also tried Markdown Navigator Enhanced in the meantime
  - affected inspections, at least in that all square brackets are expected to represent references
  - but then standard Markdown added support for PlantUML and Mermaid diagramming <br/><br/>
- so try sticking with standard Markdown for now

### > Proofreading <
- [ ] document
  - Editor : Inspections : Proofreading
  - applies to all coding languages and commit messages
  - document 

### > language Markdown <
- document: languages/Markdown
- use standard Markdown
- all Markdown code, including in commit messages, is fully proofread and inspected for code issues
### > Implementation <

- [ ] Document Code Inspections #114 
- Preferences : Editor: Inspections; [Code inspections﻿](https://www.jetbrains.com/help/idea/code-inspection.html) <br><br>

- [ ] adopt Markdown code style #115 <br><br>

##### Proofreading
- [ ] Editor: Proofreading Settings to default
- settings: Editor : Proofreading : Grammar contains Exceptions list <br><br>
- [ ] reset Inspections profile to Default
- [ ] new Inspections profile 'cebcar'
- [ ] reset Grammar rules: enable all for US English
- [ ] docs pass complete inspection

#### >> apply language injections to code blocks <<
- [ ] Preferences | Editor | Intentions
  - apply coding assistance (also maybe inspection checking) to code blocks
- [ ] check for language specification for all code blocks
