### ISSUE TITLE
recover existing Tuxedo docs

### ISSUE THREAD

**Issue by carolclark** [cebcar/Tuxedo-ij#42]
### recover existing Tuxedo docs #42

- [x] copy in existing documentation folder from ~/Dev/Tuxedo-w-bad-branch
- [x] look for changes from ~/Dev folders:
  - TechDocs-210615
  - Tuxedo Docs
  - TechDocs-recent
  - TechDocs start
  - Tuxedo3
- [x] update tools/IntelliJ.md from copy at ~/Dev
- [x] verify that
```shell
alias gtb='branchlist=".cebcar/branchlist"; git branch | grep -n "[a-z,A-Z]" > $branchlist; cat $branchlist; echo -n "Select: "; read lineno; tb=$(cat $branchlist | grep "$lineno:" | cut -c 5-); echo "tb: $tb"'
```
and 
```shell
git for-each-ref --sort=committerdate refs/heads/ --format='%(committerdate:short) %(refname:short)'
```
were picked up by updates to aliases.zsh and Git.md; add if not <br/><br/>

- [x] update docs with content from 'Reopen Project Tuxedo' below #58

#### Git

- [x] add:
> git rebase -i <br/><br/>

#### RepoProject
- [x] add to entities/RepoProject.md:
Our JetBrains repositories are linked to GitHub repos.
The code record is the underlying git repository, and repository problems may be dealt with using command-line git.

#### IntelliJ
- [x] IntelliJ
- .gitignore: add macOS, JetBrains content via gitignore.io
- if necessary, add project module ".idea" for .idea directory <br/><br/>

#### obtain GitHub Personal Access Token
- GitHub: [Create Personal Access Token](https://github.com/cebcar/Tuxedo-w-bad-branch/blob/main/TechDocs/DevOps/tools/GitHub.md#create-personal-access-token) "JetBrains-GitHub Integration: &lt;projectName&gt;"; copy content to clipboard

#### get repository from Version Control
- *close open project, if any, to get welcome screen with 'get from VCS' option*
- supply:
  - repository URL
  - directory of the new project
- press Enter or click Clone<br/><br/>

#### connect to settings repository
File : Manage IDE Settings : Settings Repository
  - select cebcar/ij-settings; overwrite local

#### expand .gitignore

- [gitignore.io](https://www.toptal.com/developers/gitignore): add content for macOS and JetBrains
- remove duplicate lines ".DS_Store" and "Workspace.xml"
- inspect

#### interim commit /todo/ remove; nothing to commit /
- with gitignore under control, we can make a commit

##### GitHub
- ~configure [GitHub](https://github.com/cebcar/Tuxedo-w-bad-branch/blob/main/TechDocs/DevOps/tools/GitHub.md#github)~

##### Git
- ~configure [Git](https://github.com/cebcar/Tuxedo-w-bad-branch/blob/main/TechDocs/DevOps/tools/Git.md#git)~

/todo/ add: delete git repository: `rm -rf .git` to docs /

##### Tasks
- configure [Tools: Tasks](https://github.com/cebcar/Tuxedo-w-bad-branch/blob/main/TechDocs/DevOps/tools/IntelliJ.md#tasks)
- configure [Tools: Servers: server GitHub](https://github.com/cebcar/Tuxedo-w-bad-branch/blob/main/TechDocs/DevOps/tools/IntelliJ.md#tasks-servers-server-github)

##### Scopes
- configure  [Appearance &amp; Behavior : Scopes](https://github.com/cebcar/Tuxedo-w-bad-branch/blob/main/TechDocs/DevOps/tools/IntelliJ.md#scopes)

##### Issue Navigation
- configure [Issue Navigation](https://github.com/cebcar/Tuxedo-w-bad-branch/blob/main/TechDocs/DevOps/tools/IntelliJ.md#issue-navigation)

/todo/ camel humps: honor on double click off /
#### ensure .idea folder is Version Controlled
- if necessary, add .idea as a module

/todo/ update file templates: names cd.tool, cd.color
/todo/ update scopes /

#### commit to Version Control
- Tag and Commit
  - add annotated tag "vYYMM.0.2" -m "add existing documentation"
- commit; push
