### ISSUE TITLE
back to IntelliJ IDEA

### ISSUE THREAD

**Issue by carolclark** [cebcar/Tuxedo-ij#43]
### > Background <

- Sometime during recovery from our Fetch (actually, probably insufficient branch control) problem, 
our IntelliJ settings were lost for a while.
  - could have been caused while constantly creating and recreating projects, including opening one in WebStorm
  - affected all settings, at least intermittently
    - normally, some settings including our custom Keymap, remain
    - in this case, those settings appear inconsistently, as well as our connection to our IntelliJ settings repository ij-settings
  - IntelliJ.md is intended to include documentation of both sets of settings sufficient for reconstruction <br/><br/>

- File | New..: also frequently, and intermittently as far as we could tell:
  - IntelliJ displayed a list of available filetypes including only project, module, scratch, data source, and driver sections
  - contained no content filetypes, and required at least restart before any of our content filetypes appeared
  We suspect that incorrect template content could have been the cause of or a contributor to this problem <br/><br/>

- We also tried to implement Inspection settings all at once, before continuing with other work. As a result, we believe that these settings are not optimal and that we should reimplement inspections and their setting more gradually. <br/><br/>

- We deleted the IntellliJ IDEA data from "~/Library/Application Support/JetBrains",  and IntelliJ IDEA is working as expected. <br/><br/>

######  Update 2021-11-08
- File > New...
  - we are now using rcN to create a new generic file; then establish the type by file extension, and the starting content via Live Template
    - problem may have beed caused by an invalid Live Template
    - we never got IntelliJ file templates to work

##### switch to WebStorm

We had switched to WebStorm
Reasons are described in detail below, but basically:
- we realized that we would be working largely in Web delevopment, and WebStorm seemed a better fit
- IntelliJ IDEA was broken anyway: its File | New | File was seriously broken
  - most items were missing, including New File...
  - we could not find the relevant "~/Library/Application Support" folder to delete existing (broken) IntelliJ settings

Due to the New File problem, we had started using WebStorm.

##### back to IntelliJ IDEA

Then we found out that:
- **IntelliJ supports multiple modules within a project (Tuxedo), but WebStorm does not.**
- The relevant IDE settings are at "~/Library/Application Support/JetBrains", not "IntelliJ" or "IDEA" as we had expected. 
 
So will be switching back to IntelliJ IDEA.
Consider using WebStorm when we start building a full new website with javascript, React, ...

- [x] initial WebStorm documentation #37

- [ ] preserve WebStorm settings #41

- [ ] Clean and Rebuild IDEA settings #117
  - from IDEA, while WebStorm is still the active IDE

-  back to IntelliJ
