### ISSUE TITLE
implement ZenHub Sprints

### ISSUE THREAD

**Issue by carolclark** [cebcar/Tuxedo-ij#47]
### implement ZenHub Sprints cebcar/Tuxedo-ij#47

Realistically, we may be too small to use automated Sprints. This issue will probably be closed.

#### manual 1-Week Sprints
- [ ] manual 1-Week Sprints cebcar/Tuxedo#39

#### 2-week ZenHub Sprints
- [ ] 2-week ZenHub Sprints cebcar/Tuxedo-ij#70

#### automatic ZenHub sprints
- [ ] automatic ZenHub sprints cebcar/Tuxedo-ij#28
