### ISSUE TITLE
Establish Browsers

### ISSUE THREAD

**Issue by carolclark** [cebcar/Tuxedo-ij#51]
### > Background <
/todo/
- consider [BrowserSync](https://browsersync.io) to support testing, etc in absence of Chrome plugin
  - see also StackOverflow: [WebStorm and Firefox - sync](https://stackoverflow.com/questions/38765132/webstorm-and-firefox-sync)

### > Implementation <

[How to Install and Use Firefox on iOS](https://www.pcmag.com/how-to/how-to-install-and-use-firefox-on-ios)

##### tool Firefox
- [x] tool Firefox #45

##### sync Firefox across devices
- [ ] sync Firefox across devices #85

##### Firefox extension ZenHub #52
- [ ] Firefox extension ZenHub

##### Firefox Marketplace #54
- [ ] Firefox Marketplace

##### Firefox Extension JetBrains #53
- [ ] Firefox Extension JetBrains

##### Firefox Developer version #55
- [ ] Firefox Developer version
