### ISSUE TITLE
TODO Support

### ISSUE THREAD

**Issue by carolclark** [cebcar/Tuxedo-ij#63]
### TODO Support #63

IntelliJ supports embedding formatted TODO comments in document
- we and failed tried to implement

- we tried and failed to implement IntelliJ TODO for IntelliJ Markdown
  - see [TODO comments﻿](https://www.jetbrains.com/help/idea/using-todo.html)
  - per Stack Overflow, efforts to do this have been tried by others and have failed
    - it may work only in some languages, including Java, in IDEA <br/><br/>

### >  Initial Implementation <
- document TODO format at IntelliJ.md/Conventions
  - format: "/todo[-qualifier]/ *further information* /" for markdown
  - this is searchable - search for "/todo") or, if applicable, "todo-*qualifier*
  - not hard to type
  - could be translated in future to IntelliJ Platform TODO if relevant

#### Initial TODO Support
- [ ] Initial TODO Support #64

#### support TODO per language
- support TODO per development language
- [ ] file languages/Markdown.md
- [ ] adopt format for languages/ documents
  - includes TODO format
