### ISSUE TITLE
Markdown Nav Enhanced #8

### ISSUE THREAD

**Issue by carolclark** [cebcar/Tuxedo-ij#8]
#### Evaluate for possible adoption: accepted
- [x] Evaluate for possible adoption
- many great features, including export to location as HTML (publish our TechDocs website)
- **very difficult to read for some features (eg. links) under darcula**
  - try for awhile to see if it's usable
    - 05/11/2021 figured out how to style  in Preferences with custom css, starting with Material theme
- accepted

#### fix inspection issues
- [ ] fix inspection issues

#### review and  edit configuration
- [ ] review and  edit configuration

#### add more css styles
- [ ] add more css styles
  - ~~tentatively Material theme credit [markdown-plus-plus](https://github.com/Edditoria/markdown-plus-plus)~~
  - MdNav has new rendering style
    - like ease of finding headers
    - [ ] fix: table style with darcula is too dark to read the table
      - workaround: temporarily change IntelliJ theme to light<br/><br/>

#### review mdNav features
- [ ] review mdNav features
  - see [idea-multimarkdown](https://github.com/vsch/idea-multimarkdown/wiki)

#### publish technical documentation
- [ ] publish technical documentation
- via wiki?
  - [Documenting your projects on GitHub](https://guides.github.com/features/wikis/#creating-your-wiki)
  - wiki does not support multiple folders
    - use topic in filename (replace entities/RepoProject.md with entities-RepoProject.md (or entity-RepoProject.md)?)
  - normal solution, renaming documents to &lt;folder&gt;-&lt;title&gt;, would make it much harder to find files in IntelliJ
- via export to HTML?
  - this is workable in the short term
    - it shows the source text (definitely readable) instead of the rendered content
    - writes to ~/Dev/&lt;project&gt;/exportToHtml/&lt;filename&gt;.md.html
      - not available online

## > issue dependencies:
- enables: enhanced support for Mermaid and PlantUML<br/><br/>

## >> Documentation <<
- [ ] documentation content: update; copy to IntelliJ documentation file

# Markdown Navigator
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;IntelliJ Plugin [Markdown Navigator](http://vladsch.com/product/markdown-navigator)
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;*plugin for Markdown language support on IntelliJ IDEs*<br/>
## Markdown Navigator Tool

(content)

## *Markdown Navigator Profile*
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;IntelliJ Plugin [Markdown Navigator](http://vladsch.com/product/markdown-navigator)
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;*plugin for Markdown language support on IntelliJ IDEs*<br/>
**Version**: 3.0
**License**: Apache 2.0
**Source**: IntelliJ plugin
**Obtained**: purchased  04/28/2021 ($10/firstYr; $8second; then $6)
**CriticalData**: .idea/markdown-navigator.xml and .idea/markdown-navigator-enh.xml
**Documentation**: [idea-multimarkdown](https://github.com/vsch/idea-multimarkdown/wiki)

### Markdown Navigator Configuration
- IntelliJ Prefs @ Languages &amp; FrameWorks : Markdown : Stylesheet
  - Custom CSS: add Material-based settings; credit [markdown-plus-plus](https://github.com/Edditoria/markdown-plus-plus)
```css
body {
    background-color: #263238;
}

a:link {
    color: #F78C6C;
}
```    

### Markdown Navigator Alternatives Considered
- #### IntelliJ default Markdown support
  - rejected: Markdown Navigator has
    - many great features, including export to location as HTML (publish our TechDocs website)
    - minimal cost

**Comment by carolclark** [comment]
using standard markdown for now
