### ISSUE TITLE
pipeline Roadmap

### ISSUE THREAD

**Issue by carolclark** [cebcar/Tuxedo-ij#84]
### pipeline Roadmap #84

add pipeline Roadmap to ZenHub Board

- [x] remove label Initialtive Epic; use similar red color for Roadmap Epic
- [x] add pipeline Roadmap to Board just before pipeline Epics
- [x] rename initiatives/Initiatives.md to diagrams/WorkBreakdown.md
- [x] update documentation (ZenHub; Workspace; RepoProject; Initiatives)
