### ISSUE TITLE
Info Access and Security

### ISSUE THREAD

**Issue by carolclark** [cebcar/Tuxedo-ij#97]
### Info Access and Security cebcar/Tuxedo-ij#97

*improve and expand our access to C &amp; C Software information*
*review security, including repository backup*

#### > Repository Backup
- [ ] backup GitHub data cebcar/Tuxedo-ij#2

#### > Improve Access to our Technical Documentation
- [ ] publish markdown documentation
  - establish website we can access comfortably
    - current C &amp; C Software website hosted by GoDaddy
      - we cannot currently access it, which is frustratingly common
      - we do not understand its structure or how is was set up
      - we need that account for domain registration, but
         its additional hosting costs more that we would like
    - IntelliJ can deploy to a local server
      - still need markdown to html conversion
       - then it's still only available locally
    - [w3c Schools Spaces](http://www.w3schools.com/spaces/)
      - free account would probably be sufficient until we need multiple sites
      - paid account for multiple sites @ $10 would be sufficient for currently expected need
      - w3 speaks our language
      - "move web hosting to w3c schools?" cebcar/Tuxedo#52
    - other web hosting service

#### > Set up w3spaces
Website: [cebcar](https://cebcar.w3spaces.com)
Developer portal: [cebcar-spaces](https://spaces.w3schools.com)

#### > Improve Keymaps
  - keymaps are currently formatted in a very sparse format intended for printing
  - [ ] use HTML grid to improve formatting
  - [ ] iPad format for use at computer
    - format with linkable subgroups; see [Keyboard Shortcuts: macOS Keymap](https://www.jetbrains.com/help/idea/reference-keymap-mac-default.html)

#### > make TechDocs compliant with IntelliJ inspections
  - [ ] activate and support code inspections
  - [ ] activate inspections for git messages

#### > Improve Security for our Technical Information
- [ ] backup our GitHub repos

#### > automate software installation and configuration
- self-documenting scripts would be far preferable to our current system of attempting to document all installation and configuration for reimplementing as needed

#### > recover legacy documentation
- [ ] get previous repo data cebcar/Tuxedo#26
