### ISSUE TITLE
provide web access for TechDocs

### ISSUE THREAD

**Issue by carolclark** [cebcar/Tuxedo-ij#98]
### provide web access for TechDocs cebcar/Tuxedo-ij#98

- [x] try w3spaces for web hosting cebcar/Tuxedo#52

##### w3spaces
my space: [cebcar](https://cebcar.w3spaces.com)
for editing: [cebcar-space](https://spaces.w3schools.com)

This will work at least for for starters.

- [x] activate Basic plan at w3spaces

- [ ] document w3spaces as a service cebcar/Tuxedo#65

##### upload Keymaps
- [ ] add the index.html supplied by Spaces to TechDocs/index.html
- [ ] edit index.html to provide table of contents for Keymaps, which are already in html
- [ ] from [cebcar-space](https://spaces.w3schools.com), upload TechDocs

##### add per-document ToC for TechDocs files
- [ ] choose a ToC generator to start
- [ ] generate ToCs <br><br>
